(library
 (instrumentation
  (backend bisect_ppx))
 (name gvecdb)
 (public_name gvecdb)
 (libraries lmdb capnp bigstringaf stdint unix threads ocaml_simd.avx stdlib_stable)
 (foreign_stubs
  (language c)
  (names msync_stubs)
  (flags (:standard -march=native -O3)))
 (modules
  common
  types
  keys
  store
  props_capnp
  msync
  float32_vec
  bitset
  int_heap
  int_topk
  vector_file
  knn
  hnsw
  hnsw_page
  hnsw_mvcc
  schema
  schema_registry
  dynamic_reader
  filter
  gvecdb))
