(library
 (name bench_common)
 (modules bench_common)
 (foreign_stubs (language c) (names bench_stubs))
 (libraries gvecdb yojson bigstringaf unix))

(executable
 (name bench_ann)
 (modules bench_ann)
 (libraries bench_common gvecdb yojson bigstringaf unix))

(executable
 (name bench_insert)
 (modules bench_insert)
 (libraries bench_common gvecdb yojson bigstringaf unix))

(executable
 (name bench_graph)
 (modules bench_graph)
 (libraries bench_common gvecdb yojson bigstringaf unix))

(executable
 (name bench_props)
 (modules bench_props)
 (libraries bench_common gvecdb yojson test_schemas capnp bigstringaf stdint unix))

(executable
 (name bench_crash)
 (modules bench_crash)
 (libraries bench_common gvecdb yojson bigstringaf unix))

(executable
 (name bench_concurrent)
 (modules bench_concurrent)
 (ocamlopt_flags (:standard -alert -do_not_spawn_domains -alert -unsafe_multidomain))
 (libraries bench_common gvecdb yojson bigstringaf unix))
